const cheerio = require('cheerio');
const axios = require('axios');

const urls = [
    'https://www.wta.org/go-hiking/hikes/iron-bear',
    'https://www.wta.org/go-hiking/hikes/clear-lost',
    'https://www.wta.org/go-hiking/hikes/heart-lake-via-lily-basin-trail',
    'https://www.wta.org/go-hiking/hikes/badger-mountain-1',
    'https://www.wta.org/go-hiking/hikes/silver-falls',
    'https://www.wta.org/go-hiking/hikes/little-bear-trail',
    'https://www.wta.org/go-hiking/hikes/lake-ingalls',
    'https://www.wta.org/go-hiking/hikes/church-mountain',
    'https://www.wta.org/go-hiking/hikes/magnuson-park',
    'https://www.wta.org/go-hiking/hikes/poo-poo-point',
    'https://www.wta.org/go-outside/hikes/wallula-gap-east',
    'https://www.wta.org/go-hiking/hikes/colchuck-lake',
    'https://www.wta.org/go-hiking/hikes/ring-hill-forest',
    'https://www.wta.org/go-hiking/hikes/coal-creek-falls',
    'https://www.wta.org/go-hiking/hikes/margarets-way',
    'https://www.wta.org/go-hiking/hikes/cherry-creek-falls',
    'https://www.wta.org/go-hiking/hikes/mount-persis',
    'https://www.wta.org/go-hiking/hikes/mailbox-peak-old-trail',
    'https://www.wta.org/go-hiking/hikes/mailbox-peak',
    'https://www.wta.org/go-hiking/hikes/wallace-falls',
    'https://www.wta.org/go-hiking/hikes/deception-pass-headlands',
    'https://www.wta.org/go-hiking/hikes/denny-creek',
    'https://www.wta.org/go-hiking/hikes/melakwa-lake',
    'https://www.wta.org/go-hiking/hikes/poo-poo-point-chirico-trail',
    'https://www.wta.org/go-hiking/hikes/old-robe-canyon',
    'https://www.wta.org/go-hiking/hikes/cedar-butte',
    'https://www.wta.org/go-hiking/hikes/franklin-falls',
    'https://www.wta.org/go-hiking/hikes/north-lake',
    'https://www.wta.org/go-hiking/hikes/driveway-butte',
    'https://www.wta.org/go-hiking/hikes/diablo-lake',
    'https://www.wta.org/go-hiking/hikes/little-si',
    'https://www.wta.org/go-hiking/hikes/oyster-dome',
    'https://www.wta.org/go-hiking/hikes/lake-22-lake-twenty-two',
    
]